### ISSUE TITLE
Can you upload your datasets used here? Thx

### ISSUE THREAD

**Issue by Linjian-PA** [S-Stergiadis/MODIS-LST-downscaling-with-RFR#1]

**Comment by S-Stergiadis** [comment]
I am sorry but the datasets are from usgs and I don't have the right to
upload them.

Στις Πέμ, 6 Απρ 2023, 09:14 ο χρήστης LinJian-Met-AI <
***@***.***> έγραψε:

**Comment by Linjian-PA** [comment]
Okay.. Could you leave the 'request json' file you used to extract the Athens datasets?

**Comment by S-Stergiadis** [comment]
I didn't do a manual pull, I used a website with a user interface to narrow
down  the available data and then downloaded them from there.

Στις Πέμ, 6 Απρ 2023, 09:55 ο χρήστης LinJian-Met-AI <
***@***.***> έγραψε:

**Comment by Linjian-PA** [comment]
Okay , got it. THX!
